### ISSUE TITLE
Bug Report: lmql playground throws IndexError when running locally

### ISSUE THREAD

**Issue by pavelerokhin** [eth-sri/lmql#102]
### Description
When attempting to run the `lmql playground` locally with the command `lmql serve-model google/electra-base-discriminator`, an error occurs during the execution. The error traceback suggests that the lmql package encounters an IndexError: list index out of range while initializing the VocabularyMatcher class.

### Steps to Reproduce
1. `pip3.11 install lmql\[hf\]`
2. `lmql serve-model google/electra-base-discriminator` to serve the LM.
3. `lmql playground` to run it locally locally.
4. try to execute the following lmql code: 
```python
import lmql

argmax
    "Hello[WHO]"
from
    lmql.model("google/electra-base-discriminator")
where
    STOPS_AT(WHO, "\n") and len(TOKENS(WHO)) < 10
```

Expected Behavior
The lmql playground should interpret successfully.

### Actual Behavior
The following error is encountered during the initialization process:

```plaintext
App started running...
Traceback (most recent call last):
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ops/token_set.py", line 50, in init
    with cachefile(matcher_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/caching.py", line 63, in cachefile
    raise FileNotFoundError("Cache file {} does not exist".format(path))
FileNotFoundError: Cache file matcher-google-electra-base-discriminator-TransformersTokenizer.pkl does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ui/live/live.py", line 108, in <module>
    LiveApp.cli()
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ui/live/livelib.py", line 55, in cli
    return asyncio.run(LiveApp.async_cli())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ui/live/livelib.py", line 92, in async_cli
    result = await endpoint.fct(input, *endpoint_args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ui/live/live.py", line 74, in lmql
    result = await lmql.run(code, output_writer=output_writer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/__init__.py", line 90, in run
    return await q(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/lmql_runtime.py", line 175, in __acall__
    results = await interpreter.run(self.fct, **query_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/interpreter.py", line 664, in run
    self.root_state = await self.advance(self.root_state)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/interpreter.py", line 268, in advance
    await continue_for_more_prompt_stmts()
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/interpreter.py", line 257, in continue_for_more_prompt_stmts
    await query_head.continue_()
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/multi_head_interpretation.py", line 140, in continue_
    await self.handle_current_arg()
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/multi_head_interpretation.py", line 112, in handle_current_arg
    await self.advance(res)
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/multi_head_interpretation.py", line 89, in advance
    await self.handle_current_arg()
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/multi_head_interpretation.py", line 111, in handle_current_arg
    res = await fct(*self.current_args[1], **self.current_args[2])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/interpreter.py", line 100, in set_model
    self.interpreter.set_model(model_name)
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/runtime/interpreter.py", line 212, in set_model
    VocabularyMatcher.init(self.model.get_tokenizer())
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ops/token_set.py", line 54, in init
    VocabularyMatcher._instance = VocabularyMatcher(tokenizer, tokenizer.model_identifier)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparql/venv/lib/python3.11/site-packages/lmql/ops/token_set.py", line 24, in __init__
    self.space_repr = self.tokenizer.tokenize(" ")[0]
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
App finished running with exit code 1
```

### Error Details
The error occurs in the VocabularyMatcher class within the token_set.py module of the lmql package. The tokenizer.tokenize(" ") call results in an empty list, causing the IndexError when accessing the first element.

### Environment
Operating System: MacOS Monterey 
Python Version: 3.11.3
Pip Version: pip 23.0.1 (python 3.11)
lmql Version: lmql v0.0.6.4
  commit: 222a28a05e62db6163d61258627327880639ea94
  path: /usr/local/lib/python3.11/site-packages/lmql
  build on: Thu Jun  8 17:29:11 CEST 2023

**Comment by lbeurerkellner** [comment]
Thank you for this very thorough bug report. It seem like the tokenizer shipped in `google/electra-base-discriminator` has trouble tokenising a single space ` ` character. This would need some special handling on our end.

However, inspecting the model card here "https://huggingface.co/google/electra-base-discriminator", it seems this is not actually a [AutoModelForCausalLM](https://huggingface.co/docs/transformers/v4.30.0/en/model_doc/auto#transformers.AutoModelForCausalLM), but a different type of model not compatible with the HuggingFace `generate()` method. This means the linked model is not actually compatible with generating text using LMQL.

**Comment by pavelerokhin** [comment]
Thank you for your kind response!
