### ISSUE TITLE
Assertion error (no log probs > truncation threshold). Warning: All continuation token fall below truncation threshold

### ISSUE THREAD

**Issue by bglazer** [eth-sri/lmql#115]
I'm running the LMQL server with a local HuggingFace Transformer model (https://huggingface.co/HuggingFaceH4/starchat-beta).

I am receiving a warning and Assertion error when I try any LMQL query (stack trace below). The warning suggests that I increase the truncation factor, but it's not clear to me how I would do that. This error persists after restarting the LMQL server. 

For the purpose of illustration the following LMQL query gives the same error:

```
    argmax 
        "Say 'this is a test':[RESPONSE]" 
    from 
        '/home/bglaze/.cache/huggingface/hub/models--HuggingFaceH4--starchat-beta/snapshots/b1bcda690655777373f57ea6614eb095ec2c886f/'
    where 
        len(TOKENS(RESPONSE)) < 10
```

Here is the stack trace: 

```
WARNING: all continuation token fall below truncation threshold. This is likely due to a too small truncation factor. Try increasing it. Continuing with the top 1 token.
Traceback (most recent call last):
  File "/home/bglaze/protocolbot/test_lmql.py", line 20, in <module>
    print(loop.run_until_complete(joke()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/lmql_runtime.py", line 175, in __acall__
    results = await interpreter.run(self.fct, **query_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/interpreter.py", line 773, in run
    async for _ in decoder_fct(prompt, **decoder_args):
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/dclib/decoders.py", line 22, in argmax
    h = h.extend(await model.argmax(h, noscore=True))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_array.py", line 332, in extend
    return DataArray(apply_componentwise(op_extend, self.sequences, other.sequences, "extend", allow_mismatch_keys=False), dims=self.shape)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_array.py", line 258, in apply_componentwise
    result[k] = op(pool_a, pool_b)
                ^^^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_array.py", line 329, in op_extend
    extended_seqs.append(sq.extend(Continuation(t, s, u)))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_seq.py", line 333, in extend
    return DecoderSequence(
           ^^^^^^^^^^^^^^^^
  File "/home/bglaze/miniconda3/envs/protocolbot/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_seq.py", line 85, in __init__
    assert all([p > DecoderSequence.truncation_threshold for p in logprobs]) if logprobs is not None else True
```

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. Can this be reproduced just with the snapshot you show, or also just with the regular starchat?

**Comment by bglazer** [comment]
I'm unsure whether this is an issue with this particular snapshot. The snapshot listed above is the latest from the starchat repo on HuggingFace. 

I have observed that this issue only occurs when I serve the model with load_in_8bit. The issue is resolved when I use load_in_4bit instead:

`lmql serve-model --model <model_dir> --load_in_4bit True --cuda`

I'm using bitsandbytes=0.40.0.post4, which I suspect is the root cause, rather than LMQL. So I'm closing this comment. Thanks for the support!

**Comment by lbeurerkellner** [comment]
Quantization could be an issue, as the error indicates that all available token probabilities were so low, that LMQL removed them from consideration, as the result would have been very noisy. Could be handled a bit more liberally on our end, though, I admit.

**Comment by Reekomer** [comment]
I am facing this issue with llama.cpp using Mistral.

# Server Side
` [Loading llama.cpp model from llama.cpp:/code/lmql_server/models/TheBloke/Mistral-7B-Instruct-v0-1-GGUF/mistral-7b-instruct-v0.1.Q5_K_S.gguf  with  {'loader': None, 'temp': 0.5, 'n_gpu_layers': 100, 'n_ctx': 50000, 'device_map': 'auto'} ]`

# Client Side
```python
from __future__ import annotations

import lmql
import nest_asyncio

nest_asyncio.apply()

model = "mistral-7b-instruct"
@lmql.query
def hello():
    '''lmql
    from dataclasses import dataclass
    from typing import List

    MODEL_NAME = "llama.cpp:/code/lmql_server/models/TheBloke/Mistral-7B-Instruct-v0-1-GGUF/mistral-7b-instruct-v0.1.Q5_K_S.gguf"
    TOKENIZER_PATH = "mistralai/Mistral-7B-Instruct-v0.1"

    @dataclass
    class Basket:
        price: int
        items: int
        quantity: int

    argmax(max_len=10000)
        """
        "Food": [BASKET]
        """
        return BASKET
    from
        lmql.model(MODEL_NAME, tokenizer=TOKENIZER_PATH, endpoint="localhost:9999/")
    where
        type(BASKET) is Basket and len(TOKENS(BASKET)) < 50
    '''


result = hello()
```

# Issue
WARNING: all continuation token fall below truncation threshold. This is likely due to a too small truncation factor. Try increasing it. Continuing with the top 1 token.
---------------------------------------------------------------------------
```AssertionError                            Traceback (most recent call last)
/home/ubuntu/Desktop/repos/experiments/prototypes/quantize_model/test-constraint-mistral.py in line 39
     12 @lmql.query
     13 def hello():
     14     '''lmql
     15     from dataclasses import dataclass
     16     from typing import List
   (...)
     35         type(BASKET) is Basket and len(TOKENS(BASKET)) < 50
     36     '''
---> 39 result = hello()

File ~/miniconda3/envs/low_code_gen/lib/python3.10/site-packages/lmql/api/queries.py:148, in query..lmql_query_wrapper(*args, **kwargs)
    146 @wraps(fct)
    147 def lmql_query_wrapper(*args, **kwargs):
--> 148     return module.query(*args, **kwargs)

File ~/miniconda3/envs/low_code_gen/lib/python3.10/site-packages/lmql/runtime/lmql_runtime.py:204, in LMQLQueryFunction.__call__(self, *args, **kwargs)
    202 def __call__(self, *args: Any, **kwargs: Any) -> Any:
    203     if not self.is_async:
--> 204         return call_sync(self, *args, **kwargs)
    206     return self.__acall__(*args, **kwargs)

File ~/miniconda3/envs/low_code_gen/lib/python3.10/site-packages/lmql/runtime/loop.py:36, in call_sync(lmql_query_function, *args, **kwargs)
...
---> 85     assert all([p > DecoderSequence.truncation_threshold for p in logprobs]) if logprobs is not None else True
     87     if type(input_ids_or_str) == str:
     88         assert False, "constructing dc.seq() directly from string is not supported anymore"

AssertionError:
```

Is there a way to increase the truncation factor?

**Comment by lbeurerkellner** [comment]
This has re-surfaced and now been fixed in 0.7.1, see via https://github.com/eth-sri/lmql/issues/135#issuecomment-1759658342
