### ISSUE TITLE
Cannot run lmql-serve - SyntaxError

### ISSUE THREAD

**Issue by jumski** [eth-sri/lmql#130]
I anticipate I am missing something fundamental or making some basic mistake - bear with me :bow:

I tried to run **lmql-serve** to serve the hugging face quantized model with the following command:

```shell
poetry run lmql serve-model --loader auto-gptq --cuda --static TheBloke/Llama-2-7B-GPTQ
``` 
<details><summary>other commands i tried</summary>
<p>

```shell
poetry run lmql serve-model --loader auto-gptq --cuda TheBloke/Llama-2-7B-GPTQ
poetry run lmql serve-model --loader auto-gptq --static TheBloke/Llama-2-7B-GPTQ
poetry run lmql serve-model --loader auto-gptq TheBloke/Llama-2-7B-GPTQ
poetry run lmql serve-model TheBloke/Llama-2-7B-GPTQ
``` 

</p>
</details> 

## SyntaxError

But it fails with the following error:

```
Traceback (most recent call last):
  File "/home/jumski/.asdf/installs/python/3.10.9/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jumski/.asdf/installs/python/3.10.9/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/jumski/.cache/pypoetry/virtualenvs/langchain-sandbox-guzw3mW8-py3.10/lib/python3.10/site-packages/lmql/__init__.py", line 17, in <module>
    import lmql.runtime.lmql_runtime as lmql_runtime
  File "/home/jumski/.cache/pypoetry/virtualenvs/langchain-sandbox-guzw3mW8-py3.10/lib/python3.10/site-packages/lmql/runtime/lmql_runtime.py", line 12, in <module>
    from lmql.runtime.interpreter import PromptInterpreter
  File "/home/jumski/.cache/pypoetry/virtualenvs/langchain-sandbox-guzw3mW8-py3.10/lib/python3.10/site-packages/lmql/runtime/interpreter.py", line 2, in <module>
    import asyncio
  File "/home/jumski/.cache/pypoetry/virtualenvs/langchain-sandbox-guzw3mW8-py3.10/lib/python3.10/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/jumski/.cache/pypoetry/virtualenvs/langchain-sandbox-guzw3mW8-py3.10/lib/python3.10/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^^^^^
SyntaxError: invalid syntax
``` 

### lmql

I installed **lmql** via `poetry add lmql[hf]`:

```shell
❯ poetry show lmql
 name         : lmql
 version      : 0.0.6.5
 description  : A query language for language models.

dependencies
 - accelerate *
 - astunparse 1.6.3
 - numpy *
 - openai *
 - psutil *
 - termcolor *
 - tiktoken *
 - transformers >=4.28.1
``` 

### python

```shell
❯ poetry run python --version
Python 3.10.9
``` 

### OS / GPU

I'm on **Manjaro Linux**, using RTX 3090

**Comment by lbeurerkellner** [comment]
I am not familiar with poetry, but it looks like an issue with the python version you are running with. Can you provide the more details about your environment.

Note also that `--loader auto-gptq` is currently only available on 'main' not in 0.0.6.5, as we have not published a release with it.

**Comment by h3ndrik** [comment]
I got the same error when launching it via:

`lmql serve-model llama.cpp:orca-mini-3b.ggmlv3.q4_0.bin`

Debian testing , Python 3.11

**Comment by lbeurerkellner** [comment]
Can you confirm that you can run the following on your system with the same python version that you are running LMQL with:

```
python -c "import asyncio"
```

This looks to happen entirely in `asyncio` code, which is very odd.

**Comment by lbeurerkellner** [comment]
Found this, which may be related: https://github.com/pyinstaller/pyinstaller/issues/6156#issuecomment-904534078

Do you have an compatibility version of asyncio installed?

**Comment by h3ndrik** [comment]
> python -c "import asyncio"

works fine

> Do you have an compatibility version of asyncio installed?

`pip uninstall asyncio`

Wow. Now i get a different error. Seems to be the case.

**Comment by lbeurerkellner** [comment]
Has this issue been resolved by uninstalling `asyncio`? Were you able to resolve the other error that was raised?
