### ISSUE TITLE
llama.cpp: AssertionError when using distribution (overflow encountered in exp)

### ISSUE THREAD

**Issue by h3ndrik** [eth-sri/lmql#135]
Code:
```python
import lmql

@lmql.query
def hello():
    '''lmql
    argmax
        # review to be analyzed
        review = """We had a great stay. Hiking in the mountains was fabulous and the food is really good."""

        # use prompt statements to pass information to the model
        "Review: {review}"
        "Q: What is the underlying sentiment of this review and why?"
        # template variables like [ANALYSIS] are used to generate text
        "A:[ANALYSIS]" where not "\n" in ANALYSIS

        # use constrained variable to produce a classification
        "Based on this, the overall sentiment of the message can be considered to be[CLS]"
    from
        lmql.model("local:llama.cpp:orca-mini-3b.ggmlv3.q4_0.bin")
    distribution
        CLS in [" positive", " neutral", " negative"]
    '''

hello()[0].prompt
```

Error:
```bash
(venv) $ python lmql-test.py 
[Loading llama.cpp model from llama.cpp:orca-mini-3b.ggmlv3.q4_0.bin  with  {} ]
llama.cpp: loading model from orca-mini-3b.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 3200
llama_model_load_internal: n_mult     = 240
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 26
llama_model_load_internal: n_rot      = 100
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 8640
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 3B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 2098.73 MB (+  162.50 MB per state)
llama_new_context_with_model: kv self size  =  162.50 MB
/[...]/lib/python3.11/site-packages/lmql/utils/nputil.py:36: RuntimeWarning: overflow encountered in exp
  normalizer = np.sum(np.exp(a), axis=axis)
Traceback (most recent call last):
  File "[...]/lmql-test.py", line 24, in <module>
    hello()[0].prompt
    ^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/__init__.py", line 195, in lmql_query_wrapper
    return module.query(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/lmql_runtime.py", line 193, in __call__
    return call_sync(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/loop.py", line 36, in call_sync
    res = loop.run_until_complete(task)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/lmql_runtime.py", line 216, in __acall__
    results = await (ConditionalDistributionPostprocessor(interpreter).process(results))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/postprocessing/conditional_prob.py", line 59, in process
    scores = await self.score(result.prompt, distribution_values, model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/postprocessing/conditional_prob.py", line 22, in score
    scoring_results = await dcmodel.score([prompt_seq] * len(value_ids), value_ids)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_cache.py", line 481, in score
    return await asyncio.gather(*[op_score(sq, tok) for sq, tok in zip(sqs, tokens)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_cache.py", line 445, in op_score
    result: DeterministicDecoderSequence = (await self.delegate.score([continued_seq], [tok], max_batch_size, det, stop_phrase, needs_rewrite=needs_rewrite, user_data=user_data, noscore=noscore, internal=True))[0]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/models/lmtp/lmtp_dcmodel.py", line 356, in score
    results.append(make_detseq(s, scores, tokens))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/models/lmtp/lmtp_dcmodel.py", line 340, in make_detseq
    return dc.detseq(ids=np.concatenate([s.input_ids, completion[:1]], axis=0), 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_seq.py", line 673, in detseq
    return DeterministicDecoderSequence(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_seq.py", line 469, in __init__
    super().__init__(input_ids, logprobs, deterministic, stop_phrase, predecessor, user_data=user_data.copy() if user_data is not None else None, sticky_user_data_keys=sticky_user_data_keys, internal=internal)
  File "/[...]/lib/python3.11/site-packages/lmql/runtime/dclib/dclib_seq.py", line 85, in __init__
    assert all([p > DecoderSequence.truncation_threshold for p in logprobs]) if logprobs is not None else True
                                                                                ^^^^^^^^^^^^^^^^^^^^
AssertionError
```

OS: Debian testing
Python 3.11

**Comment by lbeurerkellner** [comment]
Thanks for reporting this, I can reproduce this locally. There seems to be an issue with scoring and llama.cpp.

**Comment by lbeurerkellner** [comment]
I identifier the underlying issue. Using llama.cpp models with `distribution` and scoring decoders like `beam` may currently run into issues due to incorrectly normalised logprobs. See the `llama-cpp-logits-fix` branch for the likely fix.

**Comment by h3ndrik** [comment]
Thank you. With the patch from that branch it seems to work. Now I get some distribution_values. But i still get the warning with the overflow:

```
[...]
/[...]/src/lmql/src/lmql/utils/nputil.py:36: RuntimeWarning: overflow encountered in exp
  normalizer = np.sum(np.exp(a), axis=axis)
/[...]/lib/python3.11/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
```

**Comment by charles-dyfis-net** [comment]
To add to @h3ndrik's comment above re when I reported in Discord that the warning was replaced with an AssertionError --

It turns out that the AssertionError was in fact only masking the warning; the warning is reachable for me too. (Still working on a reproducer for that assertion).

**Comment by lbeurerkellner** [comment]
To maybe help with finding a good example, what causes the issue above with `exp()` but also with truncation in general, is if the model distribution is oddly shaped/masked, such that only very low logrobs (low negative numbers) remain. I have seen this happen more with quantized models, which may be more susceptible to this.

**Comment by vade** [comment]
Hi. FWIW I just got this with a Llama CPP, running a quantized model ( llama-2-7b.Q8_0.gguf )

My LMQL program:

@lmql.query(max_len=16384, output_writer=lmql.printing)
async def lmql_evaluate_library_context(library_context: LibraryContext, available_tags = set()) -> List[str]:
	'''lmql
# argmax
sample(temperature=0.75)
   

   """
   Imagine we have a library of found footage video content which has been annotated with the following metadata categories and tags:
   """

   for category_with_tags in library_context.categories_and_tags:
      category_name = category_with_tags["category"]
      tags = category_with_tags["tags"]
      for tag in tags:
         tag_and_cat = category_name + '"' + tag + '"'
         available_tags.add(tag_and_cat)
         "{tag_and_cat}, "

   """. \n"""

   """
   Select the tags which are most pertinent to the story prompt: {library_context.video_prompt}\n\r
   """

   selected_tags = []
   for j in range(min(10, len(available_tags) )):
      "- [A_TAG]\n"
      selected_tags.extend({A_TAG})

   return selected_tags

from 
#   "openai/text-davinci-003" 
   lmql.model("llama.cpp:/app/models/llama-2-7b.Q8_0.gguf", endpoint="http://ozu-lqml-server:8080")
where 
   A_TAG in available_tags 

	'''
	
Where the input could be a JSON dict like so:

```
{
  "video_prompt": "Jack and Jill went up the hill",
  "categories_and_tags" : 
  [
    {"category" : "Character", "tags" : [ "Jack", "Jill", "Sarah", "Bob", "Bill"] },
    {"category" : "Location", "tags" : ["Hill", "Town", "Bills Office", "Sarahs House", "A planetarium", "the town garbage dump"] },
  ]
}
```

I hope thats helpful? 

Thank you

**Comment by lbeurerkellner** [comment]
From 0.7.1 on, we have changed all logprob truncation related assertion to be warnings, that can also be silenced. Further, if you encounter a warning about the truncation threshold, you can adjust it using a model parameter like so:

```
lmql.model(..., truncation_threshold=-10000)
```

This should prevent this issue in the future.

**Comment by SamGalanakis** [comment]
I am getting the same error on the current main when using 
`lmql serve-model llama.cpp:/home/sam-dev/code/vectorizer/models/dolphin-2.5-mixtral-8x7b.Q4_K_M.gguf  --n_gpu_layers -1 --n_ctx 16000`

even  with truncation_threshold=-10000

**Comment by lbeurerkellner** [comment]
Per https://github.com/eth-sri/lmql/blob/ab02526ddf9883aff4acda4e76c5a2a1cc136bf1/src/lmql/runtime/dclib/dclib_seq.py#L88, it could be that you have to go even lower. You can also print the truncated value in this line, if you want to know what the exact value is that you need to undercut.

**Comment by midsummerstudios** [comment]
I'm on version 7.3.1, and am seeing this issue running lmql-server. Interestingly, if I run with no GPU layers, things work fine. It's only if I offload layers that I see the issue. I've tried increasing and decreasing the threshold value, and also loading the model in both 8-bit and 4-bit. Nothing seems to work. Here's my server start command:
```
CMD ["lmql", \ 
    "serve-model", \ 
    "llama.cpp:/app/models/openhermes-2.5-mistral-7b.Q5_K_M.gguf", \
    "--port", "8000", \ 
    "--host", "0.0.0.0", \ 
    "--n_ctx", "1024", \
    "--n_threads", "4", \
    "--cuda", \
    "--n_gpu_layers", "-1", \
    "--verbose", "True" \
]
```
And my model instance in the client:
```
model = lmql.model(
            "llama.cpp:/app/models/openhermes-2.5-mistral-7b.Q5_K_M.gguf", 
            tokenizer="teknium/OpenHermes-2.5-Mistral-7B", 
            endpoint="lmql:8000",
        )
```

**Comment by wmiller** [comment]
I'm on version 7.3.1, and am seeing this issue running lmql-server. Interestingly, if I run with no GPU layers, things work fine. It's only if I offload layers that I see the issue. I've tried increasing and decreasing the threshold value, and also loading the model in both 8-bit and 4-bit. Nothing seems to work. Here's my server start command:
```
CMD ["lmql", \ 
    "serve-model", \ 
    "llama.cpp:/app/models/openhermes-2.5-mistral-7b.Q5_K_M.gguf", \
    "--port", "8000", \ 
    "--host", "0.0.0.0", \ 
    "--n_ctx", "1024", \
    "--n_threads", "4", \
    "--cuda", \
    "--n_gpu_layers", "-1", \
    "--verbose", "True" \
]
```
And my model instance in the client:
```
model = lmql.model(
            "llama.cpp:/app/models/openhermes-2.5-mistral-7b.Q5_K_M.gguf", 
            tokenizer="teknium/OpenHermes-2.5-Mistral-7B", 
            endpoint="lmql:8000",
        )
```

**Comment by lbeurerkellner** [comment]
Can you specify a lower truncation threshold via the option advertised in the warning message?

**Comment by wmiller** [comment]
Yes. I tried this, and get the same result:
```
model = lmql.model(
            "llama.cpp:/app/models/openhermes-2.5-mistral-7b.Q5_K_M.gguf", 
            tokenizer="teknium/OpenHermes-2.5-Mistral-7B", 
            endpoint="lmql:8000",
            truncation_threshold=-3e+50
        )
```
Warning:
```
WARNING: all continuation token fall below the current logprob truncation threshold -3e+50. This is likely due to a too low truncation threshold. Please increase the truncation threshold via lmql.model(..., truncation_threshold=...).
```
Higher values don't work either.
