### ISSUE TITLE
lmql server <model> threading error

### ISSUE THREAD

**Issue by prashiyn** [eth-sri/lmql#146]
When I run lmql serve-model tiiuae/falcon-7b-instruct

I get the following error
Exception in thread scheduler-worker:
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/site-packages/lmql/models/lmtp/lmtp_scheduler.py", line 247, in worker
    model = LMTPModel.load(self.model_identifier, **self.model_args)
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/site-packages/lmql/models/lmtp/backends/lmtp_model.py", line 51, in load
    return LMTPModel.registry["transformers"](model_name, **kwargs)
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/site-packages/lmql/models/lmtp/backends/transformers_model.py", line 18, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(self.model_identifier, **self.model_args)
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 986, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 535, in resolve_trust_remote_code
    signal.signal(signal.SIGALRM, _raise_timeout_error)
  File "/opt/homebrew/anaconda3/envs/llm/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter

Looks like the signal for model load is sent from the child thread. 
Python 3.10.11 running in conda env.

**Comment by lbeurerkellner** [comment]
Falcon does not support running in a background thread. To run in in the main thread, try running the `serve-model` command with `--single_thread`. This may have an effect on overall latency.

**Comment by freckletonj** [comment]
@lbeurerkellner Could you expound on why Falcon doesn't support running in a background thread? Any links to references or such?

I've faced endless turmoil getting Falcon to play nicely with LMQL, but, it's got the only license I can work with for a certain gig.
