### ISSUE TITLE
AssertionError: token_ids are not unique

### ISSUE THREAD

**Issue by lbeurerkellner** [eth-sri/lmql#17]
This query reliably causes an issue with the beam decoder:

```
beam(2)
    thing = "a cake"
    "Q: I'm going to make {thing}. And need help.\n"
    "A: First, you'll need the following items:\n"
    " -[ITEM]"
    items = [ITEM]
    while True:
        "[APPEND]"
        if APPEND == "\nand that's all.\n\n":
            break
        "[ITEM]"
        items.append(ITEM)
from 
    "openai/text-davinci-003"
where 
    APPEND in set([" -", "\nand that's all.\n\n"]) and
    STOPS_AT(ITEM, "\n")
```

```Traceback (most recent call last):
  File "<exec>", line 12, in cli
  File "/home/pyodide/lmql/ui/live/livelib.py", line 92, in async_cli
    result = await endpoint.fct(input, *endpoint_args, **kwargs)
  File "/home/pyodide/lmql/ui/live/live.py", line 75, in lmql
    result = await lmql.run(code, output_writer=output_writer)
  File "/home/pyodide/lmql/__init__.py", line 107, in run
    return await run_file(temp_lmql_file, output_writer=output_writer)
  File "/home/pyodide/lmql/__init__.py", line 99, in run_file
    return await module.query(**kwargs)
  File "/home/pyodide/lmql/runtime/lmql_runtime.py", line 134, in __acall__
    results = await interpreter.run(self.fct, **query_kwargs)
  File "/home/pyodide/lmql/runtime/prompt_interpreter.py", line 812, in run
    return await pool.run()
  File "/home/pyodide/lmql/runtime/prompt_interpreter.py", line 731, in run
    query_result: Optional[List[DecoderHead]] = await self.intepreter.model.query(self.initial_prompt, where, rewriter, active_prompter)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 974, in query
    return await self.adapter.query(prompt, mask_logits_processor, head_input_id_rewriter, active_prompt_rewriter, dclib_model, self.decoder_args)
  File "/home/pyodide/lmql/runtime/dclib/lmql_adapter.py", line 180, in query
    async for _ in decoder_fct(prompt_ids, **decoder_args):
  File "/home/pyodide/lmql/runtime/dclib/decoders.py", line 156, in beam_search
    h = h.extend(await model.topk_continuations(h, k=n))
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 581, in topk_continuations
    return await sequences.aelement_wise(op_topk)
  File "/home/pyodide/lmql/runtime/dclib/dclib_array.py", line 312, in aelement_wise
    result_items = await asyncio.gather(*[op_with_path(path, seqs, *args, **kwargs) for path, seqs in self.sequences.items()])
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/pyodide/lmql/runtime/dclib/dclib_array.py", line 311, in op_with_path
    return path, await op(element, *args, **kwargs)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 559, in op_topk
    assert len(token_ids) == len(set(token_ids)), "token_ids are not unique"
AssertionError: token_ids are not unique```

**Comment by lbeurerkellner** [comment]
This will be fixed in #24
