### ISSUE TITLE
[Error during generate()] shape '[1, 627, 64, 128]' is invalid for input of size 642048

### ISSUE THREAD

**Issue by ambroser53** [eth-sri/lmql#218]
I'm using LMQL with a specific huggingface model `garage-bAInd/Platypus2-70B-instruct` and it throws up the following error:

```
[Error during generate()] shape '[1, 627, 64, 128]' is invalid for input of size 642048
Traceback (most recent call last):
  File "/users/acp22ahr/guidancetesting/QAdataset/LMQL_query_QA.py", line 165, in <module>
    b = get_judgements(q)
  File "/users/acp22ahr/guidancetesting/QAdataset/LMQL_query_QA.py", line 121, in get_judgements
    executed_prog = program_quantised(
  File "/users/acp22ahr/lmql/src/lmql/api/queries.py", line 148, in lmql_query_wrapper
    return module.query(*args, **kwargs)
  File "/users/acp22ahr/lmql/src/lmql/runtime/lmql_runtime.py", line 204, in __call__
    return call_sync(self, *args, **kwargs)
  File "/users/acp22ahr/lmql/src/lmql/runtime/loop.py", line 36, in call_sync
    res = loop.run_until_complete(task)
  File "/users/acp22ahr/.conda/envs/qlora/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/users/acp22ahr/lmql/src/lmql/runtime/lmql_runtime.py", line 230, in __acall__
    results = await interpreter.run(self.fct, **query_kwargs)
  File "/users/acp22ahr/lmql/src/lmql/runtime/interpreter.py", line 1012, in run
    async for _ in decoder_fct(prompt, **decoder_args):
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/decoders.py", line 22, in argmax
    h = h.extend(await model.argmax(h, noscore=True))
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/dclib_cache.py", line 262, in argmax
    return await arr.aelement_wise(op_argmax)
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/dclib_array.py", line 318, in aelement_wise
    result_items = await asyncio.gather(*[op_with_path(path, seqs, *args, **kwargs) for path, seqs in self.sequences.items()])
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/dclib_array.py", line 317, in op_with_path
    return path, await op(element, *args, **kwargs)
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/dclib_cache.py", line 241, in op_argmax
    non_cached_argmax = iter((await self.delegate.argmax(DataArray(non_cached), **kwargs)).items())                
  File "/users/acp22ahr/lmql/src/lmql/models/lmtp/lmtp_dcmodel.py", line 249, in argmax
    return await self.sample(sequences, temperature=0.0, **kwargs)
  File "/users/acp22ahr/lmql/src/lmql/models/lmtp/lmtp_dcmodel.py", line 292, in sample
    return await sequences.aelement_wise(op_sample)
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/dclib_array.py", line 318, in aelement_wise
    result_items = await asyncio.gather(*[op_with_path(path, seqs, *args, **kwargs) for path, seqs in self.sequences.items()])
  File "/users/acp22ahr/lmql/src/lmql/runtime/dclib/dclib_array.py", line 317, in op_with_path
    return path, await op(element, *args, **kwargs)
  File "/users/acp22ahr/lmql/src/lmql/models/lmtp/lmtp_dcmodel.py", line 282, in op_sample
    tokens = await asyncio.gather(*[self.stream_and_return_first(s, await self.generate(s, temperature=temperature, **kwargs), mode) for s,mode in zip(seqs, unique_sampling_mode)])
  File "/users/acp22ahr/lmql/src/lmql/models/lmtp/lmtp_dcmodel.py", line 138, in stream_and_return_first
    buffer += [await anext(iterator)]
  File "/users/acp22ahr/lmql/src/lmql/models/lmtp/lmtp_multiprocessing.py", line 158, in generate
    async for token in self.stream_iterator(self.stream_id):
  File "/users/acp22ahr/lmql/src/lmql/models/lmtp/lmtp_multiprocessing.py", line 187, in stream_iterator
    raise LMTPStreamError(item["error"])
lmql.models.lmtp.errors.LMTPStreamError: failed to generate tokens 'shape '[1, 627, 64, 128]' is invalid for input of size 642048'
```

I'm calling the model with a `@lmql.query()` decorated function within python with the following model call within the \`\`\`lmql block
```python
from
    lmql.model("garage-bAInd/Platypus2-70B-instruct", cuda=True, inprocess=True, dtype="bfloat16")
```

I have ran the exact same script with the exact same setup for `meta-llama/Llama-2-13b-chat-hf` and had no issues. Is it model dependent and on what cases does this problem arise?

**Comment by ambroser53** [comment]
Just an added update I have now also tried with the `meta-llama/Llama-2-13b-chat-hf` model and got the same error whilst the 30b Platypus llama variant did not and ran fine.

**Comment by lbeurerkellner** [comment]
Hi, thanks for reporting this. I am running things with `meta-llama/Llama-2-13b-chat-hf` quite frequently. Could you provide a concrete prompt that fails for you, so I can reproduce on my end? That would be awesome.

**Comment by ambroser53** [comment]
Sorry that was a typo, 13b is fine it is 70b models that have this issue.

Here is the prompt I am using:

'''lmql

    argmax
        "Is question A or B a better answerable span extraction question for the given text according to the requirements\n"

        "Text: {input}\n"

        "Question A: {questionA}\n"

        "Is Question A related to the input text? [requirementA1]\n" where requirementA1 in set(["Yes", "No"])
        if "Yes" in requirementA1:
            "Is Question A a span extraction question? [requirementA2]\n" where requirementA2 in set(["Yes", "No"])
            if "Yes" in requirementA2:
                "Does the answer provided with the question match the correct answer in the text? [requirementA3]\n" where requirementA3 in set(["Yes", "No"])
                if "Yes" in requirementA3:
                    "Is the answer provided with the question concise? [requirementA4]\n" where requirementA4 in set(["Yes", "No"])


        "\nQuestion B: {questionB}\n"

        "Is Question B related to the input text? [requirementB1]\n" where requirementB1 in set(["Yes", "No"])
        if "Yes" in requirementB1:
            "Is Question B a span extraction question? [requirementB2]\n" where requirementB2 in set(["Yes", "No"])
            if "Yes" in requirementB2:
                "Does the answer provided with the question match the correct answer in the text? [requirementB3]\n" where requirementB3 in set(["Yes", "No"])
                if "Yes" in requirementB3:
                    "Is the answer provided with the question concise? [requirementB4]\n" where requirementB4 in set(["Yes", "No"])

        "\nProvide a paragraph reasoning step-by-step for which question is better: \n\n[reasoning]\n" where STOPS_AT(reasoning, "\n")

        "Given the evaluation of each question relative to the requirements, the better question is Question [answer]." where answer in set(["A", "B"])
    from
        lmql.model("meta-llama/Llama-2-70b-chat-hf", cuda=True, inprocess=True)
    '''

**Comment by ambroser53** [comment]
I am using the most recent version of LMQL

**Comment by lbeurerkellner** [comment]
Okay, I finally got some hardware to run this on. So far, with this example query (I chose some simple example questions), it seems to run fine. Can you provide a concrete `input`, `questionA`, `questionB` triplet that causes a failure?

```
questionA = "Who is the main actor of Men in Black?"
questionB = "What do you believe is the meaning of life?"
input = "The men in black was acted out by Will Smith."

"Is question A or B a better answerable span extraction question for the given text according to the requirements\n"

"Text: {input}\n"

"Question A: {questionA}\n"

"Is Question A related to the input text? [requirementA1]\n" where requirementA1 in set(["Yes", "No"])
if "Yes" in requirementA1:
    "Is Question A a span extraction question? [requirementA2]\n" where requirementA2 in set(["Yes", "No"])
    if "Yes" in requirementA2:
        "Does the answer provided with the question match the correct answer in the text? [requirementA3]\n" where requirementA3 in set(["Yes", "No"])
        if "Yes" in requirementA3:
            "Is the answer provided with the question concise? [requirementA4]\n" where requirementA4 in set(["Yes", "No"])


"\nQuestion B: {questionB}\n"

"Is Question B related to the input text? [requirementB1]\n" where requirementB1 in set(["Yes", "No"])
if "Yes" in requirementB1:
    "Is Question B a span extraction question? [requirementB2]\n" where requirementB2 in set(["Yes", "No"])
    if "Yes" in requirementB2:
        "Does the answer provided with the question match the correct answer in the text? [requirementB3]\n" where requirementB3 in set(["Yes", "No"])
        if "Yes" in requirementB3:
            "Is the answer provided with the question concise? [requirementB4]\n" where requirementB4 in set(["Yes", "No"])

"\nProvide a paragraph reasoning step-by-step for which question is better: \n\n[reasoning]\n" where STOPS_AT(reasoning, "\n")

"Given the evaluation of each question relative to the requirements, the better question is Question [answer]." where answer in set(["A", "B"])
```

Running with `meta-llama/Llama-2-70b-chat-hf`, although via `load_in_4bit`

**Comment by lbeurerkellner** [comment]
Closing this due to inactivity.
