### ISSUE TITLE
Issue running distribution clause

### ISSUE THREAD

**Issue by BedirT** [eth-sri/lmql#251]
Again me with problems on distribution :)

```
argmax
    "Select the sentiment of this sentence: [A]"
    "Sentiment: [CLS]"
from
    "openai/gpt-3.5-turbo-instruct"
distribution
    CLS in ["Pos", "Neut", "Neg"]
```
I am trying this on the playground, it just throws a weird error:

```
Client ready.
Initializing LMQL browser environment...
LMQL 0.999999 (dev) on Pyodide Python 3.10.2 (main, Jan 25 2023, 18:32:53) [Clang 16.0.0 (https://github.com/llvm/llvm-project dee009d3b5c71a340eb4ebb3cfb4

Traceback (most recent call last):
  File "<exec>", line 12, in cli
  File "/home/pyodide/lmql/ui/live/livelib.py", line 92, in async_cli
    result = await endpoint.fct(input, *endpoint_args, **kwargs)
  File "/home/pyodide/lmql/ui/live/live.py", line 83, in lmql
    result = await lmql.run(code, output_writer=output_writer, model=model, __name__="<playground query>")
  File "/home/pyodide/lmql/api/run.py", line 18, in run
    return await q(*args, **kwargs)
  File "/home/pyodide/lmql/runtime/lmql_runtime.py", line 230, in __acall__
    results = await interpreter.run(self.fct, **query_kwargs)
  File "/home/pyodide/lmql/runtime/tracing/tracer.py", line 240, in wrapper
    return await fct(*args, **kwargs)
  File "/home/pyodide/lmql/runtime/interpreter.py", line 1078, in run
    await debug_out(self.decoder_step)
  File "/home/pyodide/lmql/runtime/interpreter.py", line 967, in debug_out
    data = await dc.DecoderSequence.graph.json(diff=True)
  File "/home/pyodide/lmql/runtime/dclib/dclib_seq.py", line 68, in json
    hash = await v.json_hash()
  File "/home/pyodide/lmql/runtime/dclib/dclib_seq.py", line 244, in json_hash
    o = await self.json()
  File "/home/pyodide/lmql/runtime/dclib/dclib_seq.py", line 250, in json
    seqtext = await self.detokenized("seqtext")
  File "/home/pyodide/lmql/runtime/dclib/dclib_seq.py", line 239, in detokenized
    self.tokenizer_cache[name] = await providers[name]()
  File "/home/pyodide/lmql/runtime/dclib/dclib_seq.py", line 206, in seqtext_provider
    t = str(get_tokenizer().decode(self.input_ids))
  File "/home/pyodide/lmql/runtime/tokenizer.py", line 169, in decode
    return self.convert_bytes_to_string(input_ids)
  File "/home/pyodide/lmql/runtime/tokenizer.py", line 164, in convert_bytes_to_string
    result += self.tokenizer_impl.convert_bytes_to_string(chunk)
  File "/home/pyodide/lmql/runtime/tokenizers/pure_python_tokenizer.py", line 51, in convert_bytes_to_string
    ids = self.convert_token_bytes_to_ids(token_bytes)
  File "/home/pyodide/lmql/runtime/tokenizers/pure_python_tokenizer.py", line 64, in convert_token_bytes_to_ids
    tb = gpt3_tokenizer._entry._encoder[tb]
KeyError: 'Neutral'
App exited with status 1
```
Is it possible that `openai/gpt-3.5-turbo-instruct` is not supported with distribution is what I thought at the beginning, but it seems like it is used [in the documentation](https://lmql.ai/docs/lib/generations.html#overview)

**Comment by BedirT** [comment]
With that being said, I cannot run this model using the same sample locally as well.

```python
import lmql

m: lmql.LLM = lmql.model("openai/gpt-3.5-turbo-instruct")
print(m.score_sync("Hello", ["World", "Apples", "Oranges"]))
```

```
lmql.runtime.bopenai.openai_api.OpenAIAPILimitationError: The underlying requests to the OpenAI API with model 'gpt-3.5-turbo-instruct' are blocked by OpenAI's API limitations. Please use a different model to leverage this form of querying (e.g. distribution clauses or scoring).
```

**Comment by lbeurerkellner** [comment]
Yes, unfortunately, you ran into two edge cases here:

(1) You cannot use advanced constraining with `gpt-3.5-turbo-instruct` in the *browser distribution* of LMQL, because the tokenizer for it is not available in WebAssembly. With a local install constraining works, albeit without support for `distribution` because of OpenAI limitations.

(2) The documentation uses `gpt-3.5-turbo-instruct`, because it was written back when the restriction was not yet enforced by OpenAI. This was only announced a couple of weeks ago and came into effect very quickly (within one week of the announcement). I will make sure to update the documentation, to use a model that is still supported *today*.
