### ISSUE TITLE
Lmql playground crashes with: [WinError 2] The system cannot find the specified file

### ISSUE THREAD

**Issue by ChristophRaab** [eth-sri/lmql#298]
Hi all, 

i have the following system:

Win11; python 3.11.6 or pyhton 3.12.0
Fresh ennvironment by python-venv

i try to run `lmql playground` but got stuck with the following:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\I009200\.pyenv\pyenv-win\versions\3.12.0\Scripts\lmql.exe\__main__.py", line 7, in <module>
  File "C:\Users\I009200\.pyenv\pyenv-win\versions\3.12.0\Lib\site-packages\lmql\cli.py", line 260, in main
    command[0]()
  File "C:\Users\I009200\.pyenv\pyenv-win\versions\3.12.0\Lib\site-packages\lmql\cli.py", line 127, in cmd_playground
    if subprocess.call(["yarn", "--version"]) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I009200\.pyenv\pyenv-win\versions\3.12.0\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\I009200\.pyenv\pyenv-win\versions\3.12.0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\I009200\.pyenv\pyenv-win\versions\3.12.0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the specified file

Can you help me?
Thanks in advance

**Comment by lbeurerkellner** [comment]
Hi there :) Have you installed `yarn` and `node` in your command line environment, and are those command readily available there? Otherwise, can you maybe try running with WSL as an alternative?

**Comment by ChristophRaab** [comment]
Hi :)
I have both installed. Does that mean linux is the prefered environment?

**Comment by AndrewTHEManeri** [comment]
@ChristophRaab - did you figure this out?  I'm hitting the same issue

**Comment by AndrewTHEManeri** [comment]
Got this working - had to modify the cli.py file - anywhere subprocess was being used with the yarn command, I needed to add the argument shell=True

**Comment by jtha** [comment]
This solution worked for me as well, cheers @AndrewTHEManeri!
