### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by lbeurerkellner** [eth-sri/lmql#81]
Currently using LMQL with Python 3.11 causes an error during module loading

```
Traceback (most recent call last):
  File "/Users/ghz/workspace/lmql/read_content.py", line 2, in <module>
    import lmql
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/lmql-0.0.6.3-py3.11.egg/lmql/__init__.py", line 17, in <module>
    import lmql.runtime.lmql_runtime as lmql_runtime
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/lmql-0.0.6.3-py3.11.egg/lmql/runtime/lmql_runtime.py", line 9, in <module>
    from lmql.ops.ops import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/lmql-0.0.6.3-py3.11.egg/lmql/ops/__init__.py", line 1, in <module>
    from lmql.ops.follow_map import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/lmql-0.0.6.3-py3.11.egg/lmql/ops/follow_map.py", line 3, in <module>
    from lmql.ops.token_set import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/lmql-0.0.6.3-py3.11.egg/lmql/ops/token_set.py", line 12, in <module>
    from lmql.runtime.tokenizer import get_vocab
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/lmql-0.0.6.3-py3.11.egg/lmql/runtime/tokenizer.py", line 4, in <module>
    from lmql.runtime.tokenizers.pure_python_tokenizer import PythonBackedTokenizer
ModuleNotFoundError: No module named 'lmql.runtime.tokenizers'
```

**Comment by 5cat** [comment]
Note I dont have this issue while using lmql with python 3.11
```
pip show lmql
Name: lmql
Version: 0.0.6.3
Summary: A query language for language models.
Home-page: https://lmql.ai
Author: Luca Beurer-Kellner, Marc Fischer, Martin Vechev
Author-email: hello@lmql.ai
License:
Location: /home/cat/.cache/pypoetry/virtualenvs/resumeow-7kFCIQrj-py3.11/lib/python3.11/site-packages
Requires: astunparse, gpt3-tokenizer, numpy, openai, termcolor
Required-by:
```
```
python --version
Python 3.11.3
```
