### ISSUE TITLE
lmql.runtime.bopenai.openai_api.OpenAIStreamError

### ISSUE THREAD

**Issue by AltafHussain4748** [eth-sri/lmql#89]
Why it gives ```: (' (after receiving 0 chunks. Current chunk time``` while i am trying on playground?

**Comment by lbeurerkellner** [comment]
Can you post the full length error message? If query execution continues nonetheless, you likely experienced a timeout with an OpenAI API request which LMQL automatically handles and retries.

**Comment by AltafHussain4748** [comment]
@lbeurerkellner  here is the error
```
Client ready.
Initializing LMQL browser environment...
LMQL 0.999999 (dev) on Pyodide Python 3.10.2 (main, Jan 25 2023, 18:32:53) [Clang 16.0.0 (https://github.com/llvm/llvm-project dee009d3b5c71a340eb4ebb3cfb4

OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.5079998970031738 Average chunk time: 0.0)', 'Stream duration:', 1.5099997520446777) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 19 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.7360000610351562 Average chunk time: 0.0)', 'Stream duration:', 0.7379999160766602) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 18 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.94100022315979 Average chunk time: 0.0)', 'Stream duration:', 0.942000150680542) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 17 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5340001583099365
OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.8410003185272217 Average chunk time: 0.0)', 'Stream duration:', 1.8430001735687256) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 16 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5350000858306885
OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.9110000133514404 Average chunk time: 0.0)', 'Stream duration:', 1.9119999408721924) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 15 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5360000133514404
OpenAI: (' (after receiving 0 chunks. Current chunk time: 2.630000114440918 Average chunk time: 0.0)', 'Stream duration:', 2.630000114440918) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 14 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5410001277923584
OpenAI: (' (after receiving 0 chunks. Current chunk time: 4.993000030517578 Average chunk time: 0.0)', 'Stream duration:', 4.995000123977661) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 13 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5350000858306885
OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.8020000457763672 Average chunk time: 0.0)', 'Stream duration:', 1.8029999732971191) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 12 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5339999198913574
OpenAI: (' (after receiving 0 chunks. Current chunk time: 4.146000146865845 Average chunk time: 0.0)', 'Stream duration:', 4.148999929428101) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 11 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.990999698638916 Average chunk time: 0.0)', 'Stream duration:', 0.992999792098999) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 10 more times
Token stream took too long to produce next chunk, re-issuing completion request. Average chunk time: 0.0 Current chunk time: 1.5349998474121094
OpenAI: (' (after receiving 0 chunks. Current chunk time: 3.1609997749328613 Average chunk time: 0.0)', 'Stream duration:', 3.1619999408721924) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 9 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.0470001697540283 Average chunk time: 0.0)', 'Stream duration:', 1.0490000247955322) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 8 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.880000114440918 Average chunk time: 0.0)', 'Stream duration:', 0.8810000419616699) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 7 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.2280004024505615 Average chunk time: 0.0)', 'Stream duration:', 1.2300002574920654) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 6 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.9679999351501465 Average chunk time: 0.0)', 'Stream duration:', 0.9699997901916504) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 5 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.5480000972747803 Average chunk time: 0.0)', 'Stream duration:', 0.5500001907348633) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 4 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 1.059000015258789 Average chunk time: 0.0)', 'Stream duration:', 1.060999870300293) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 3 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.5490002632141113 Average chunk time: 0.0)', 'Stream duration:', 0.5500001907348633) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 2 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.5489997863769531 Average chunk time: 0.0)', 'Stream duration:', 0.5489997863769531) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
Retrying 1 more times
OpenAI: (' (after receiving 0 chunks. Current chunk time: 0.8330004215240479 Average chunk time: 0.0)', 'Stream duration:', 0.8350002765655518) "<class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>"
error <class 'lmql.runtime.bopenai.openai_api.OpenAIStreamError'>
Traceback (most recent call last):
  File "<exec>", line 12, in cli
  File "/home/pyodide/lmql/ui/live/livelib.py", line 92, in async_cli
    result = await endpoint.fct(input, *endpoint_args, **kwargs)
  File "/home/pyodide/lmql/ui/live/live.py", line 74, in lmql
    result = await lmql.run(code, output_writer=output_writer)
  File "/home/pyodide/lmql/__init__.py", line 100, in run
    return await run_file(temp_lmql_file, *args, output_writer=output_writer, **kwargs)
  File "/home/pyodide/lmql/__init__.py", line 92, in run_file
    return await module.query(**kwargs)
  File "/home/pyodide/lmql/runtime/lmql_runtime.py", line 144, in __acall__
    results = await interpreter.run(self.fct, **query_kwargs)
  File "/home/pyodide/lmql/runtime/interpreter.py", line 748, in run
    async for _ in decoder_fct(prompt_ids, **decoder_args):
  File "/home/pyodide/lmql/runtime/dclib/decoders.py", line 22, in argmax
    h = h.extend(await model.argmax(h, noscore=True))
  File "/home/pyodide/lmql/runtime/dclib/dclib_cache.py", line 242, in argmax
    return await arr.aelement_wise(op_argmax)
  File "/home/pyodide/lmql/runtime/dclib/dclib_array.py", line 318, in aelement_wise
    result_items = await asyncio.gather(*[op_with_path(path, seqs, *args, **kwargs) for path, seqs in self.sequences.items()])
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/pyodide/lmql/runtime/dclib/dclib_array.py", line 317, in op_with_path
    return path, await op(element, *args, **kwargs)
  File "/home/pyodide/lmql/runtime/dclib/dclib_cache.py", line 221, in op_argmax
    non_cached_argmax = iter((await self.delegate.argmax(DataArray(non_cached), **kwargs)).items())
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 431, in argmax
    return await self.sample(sequences, num_samples=1, temperature=0, **kwargs)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 539, in sample
    return await sequences.aelement_wise(op_sample)
  File "/home/pyodide/lmql/runtime/dclib/dclib_array.py", line 318, in aelement_wise
    result_items = await asyncio.gather(*[op_with_path(path, seqs, *args, **kwargs) for path, seqs in self.sequences.items()])
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/pyodide/lmql/runtime/dclib/dclib_array.py", line 317, in op_with_path
    return path, await op(element, *args, **kwargs)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 455, in op_sample
    completions: List[CompletionResult] = await self.completion_buffer(seqs, logprobs=1, **kwargs)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 373, in completion_buffer
    return await asyncio.gather(*[get_buffer(i, s) for i, s in enumerate(seqs)])
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 365, in get_buffer
    completion_result = await self.async_complete(completion_call)
  File "/home/pyodide/lmql/runtime/openai_integration.py", line 309, in async_complete
    return CompletionResult((await openai.async_buffer(await openai.Completion.create(**kwargs), tokenizer=self.tokenize_list))[input_ids.size:], completion_call.continuation_type, completion_call.logit_mask_or_fixed_id)
  File "/home/pyodide/lmql/runtime/bopenai/__init__.py", line 97, in create
    return await _api.complete(*args, **kwargs)
  File "/home/pyodide/lmql/runtime/bopenai/batched_openai.py", line 750, in complete
    return await result_fut
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/pyodide/lmql/runtime/bopenai/batched_openai.py", line 697, in complete_request_worker
    raise e
  File "/home/pyodide/lmql/runtime/bopenai/batched_openai.py", line 687, in complete_request_worker
    res = await self._create(**kwargs)
  File "/home/pyodide/lmql/runtime/bopenai/batched_openai.py", line 667, in _create
    first = await anext(res)
  File "/home/pyodide/lmql/runtime/bopenai/openai_api.py", line 60, in complete
    async for r in completion_api(**kwargs): yield r
  File "/home/pyodide/lmql/runtime/bopenai/openai_api.py", line 421, in completion_api
    raise OpenAIStreamError(last_message["error"]["message"] + " (after receiving " + str(n_chunks) + " chunks. Current chunk time: " + str(time.time() - last_chunk_time) + " Average chunk time: " + str(sum_chunk_times / max(1, n_chunks)) + ")", "Stream duration:", time.time() - stream_start)
lmql.runtime.bopenai.openai_api.OpenAIStreamError: (' (after receiving 0 chunks. Current chunk time: 0.8330004215240479 Average chunk time: 0.0)', 'Stream duration:', 0.8350002765655518)
App exited with status 1

```

**Comment by lbeurerkellner** [comment]
Are you by any chance running queries with a very long prompt?
