### ISSUE TITLE
Issue with running local .lmql files when hosting local tranformers model

### ISSUE THREAD

**Issue by TaroZ00** [eth-sri/lmql#99]
Hi, I am serving the model with 
`lmql serve-model vicgalle/gpt2-alpaca --cuda`
on localhost:8080

And I'm trying to run `lmql run lmql_experiments.lmql`

File content:
```
import lmql

argmax
    "Hello[WHO]"
from
    lmql.model("vicgalle/gpt2-alpaca")
where
    STOPS_AT(WHO, "\n") and len(TOKENS(WHO)) < 10
```

The output I got:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Scripts\lmql.exe\__main__.py", line 7, in <module>
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\lmql\cli.py", line 220, in main
    command[0]()
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\lmql\cli.py", line 41, in cmd_run
    results = asyncio.run(lmql.run_file(absolute_path, output_writer=writer))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\lmql\__init__.py", line 81, in run_file
    return await module.query(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\lmql\runtime\lmql_runtime.py", line 163, in __acall__
    query_kwargs, runtime_args = self.make_kwargs(*args, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\lmql\runtime\lmql_runtime.py", line 96, in make_kwargs
    assert self.function_context is not None, "Cannot call @lmql.query function without context."
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot call @lmql.query function without context.
```
Any idea how this could be fixed? Thanks!

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. This seems broken in 0.0.6.4. As a workaround I can recommend using lmql.query() with a string for now. 

Sorry about that.

**Comment by lbeurerkellner** [comment]
0.0.6.5 fixes this issue and you can now again use `lmql.run file.lmql` to run your query programs.
